### PR TITLE
Break long lines

### PR DESCRIPTION
**Pull request by Leopard20**
Makes it easier for syntax highlighters / linters to parse those lines.

### CODE REVIEW

**Comment by eyalz800** [comment]
Thanks, will check it out when I return from vacation

**Comment by eyalz800** [comment]
Hi, so I tried this but on my side it is more distracting to see the long lines, the thing is that this bloat appears as just one line on my editor and therefore I gracefully skip it.

Can you describe the issue you see on your side?

I really hope that https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1061r2.html gets in sometime and then we probably won't need those long lines.

**Comment by Leopard20** [comment]
> Can you describe the issue you see on your side?

Hi. The issue is not serious. I just made the change so that Visual Studio and Visual Studio Code can handle them more easily. Right now they both cause stuttering around those lines, and also cannot display the whole line (they just terminate with `...`):
image

I figured it could help users and contributors using the same editors so that they could fully read those lines. But if it's not a concern feel free to close the issue.

Unfortunately Visual Studio's linter still cannot handle the header and any file that includes the header ends up broken.
I made an issue on VS Dev community and it's currently "under consideration".

**Comment by eyalz800** [comment]
I think there is no right and wrong answer to this currently, since the long lines are kind of manual expansion of pack they seem to me not interesting for the reader - not worth expanding it into many lines so I vote to keep it the way it is for now. As for contributions, I believe it will require anyway change of the whole line so to not hurt the consistency so I assume the contributor will anyway erase the whole line. Thanks for putting up a PR and caring.

**Pull request closed without merging**
